name: GCC Release Build

on:
  push:
    paths-ignore: ['README.md']
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure (GCC Release)
        run: cmake --preset=gcc-release

      - name: Build
        run: cmake --build --preset=gcc-release
