name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-static-library:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure with Visual Studio generator (Static, C++23, no tests/docs)
        run: |
          mkdir build
          cd build
          cmake .. `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_CXX_STANDARD=23 `
            -DCMAKE_CXX_STANDARD_REQUIRED=ON `
            -DCMAKE_CXX_EXTENSIONS=OFF `
            -DBUILD_SHARED_LIBS=OFF `
            -DBUILD_TESTS=OFF `
            -DBUILD_DOCS=OFF

      - name: Build the static library in Release mode
        run: |
          cmake --build build --config Release
